title = "etcd"
disableKinds = ["taxonomy", "taxonomyTerm"]
languageCode = "en-us"

[params]
description        = "A distributed, reliable key-value store for the most critical data of a distributed system"
fontAwesomeVersion = "5.6.1"
sansSerifFont      = "Source Sans Pro"
monospaceFont      = "Fira Mono"
favicon            = "https://raw.githubusercontent.com/cncf/artwork/master/etcd/icon/color/etcd-icon-color.png"
project            = """
**etcd** is a distributed key-value store that provides a reliable way to store data across a cluster of machines. It’s open source and available [on GitHub](https://github.com/etcd-io/etcd). etcd gracefully handles leader elections during network partitions and will tolerate machine failure, including the leader.

Your applications can read and write data into etcd. A simple use case is storing database connection details or feature flags in etcd as key-value pairs. These values can be watched, allowing your app to reconfigure itself when they change. Advanced uses take advantage of etcd's consistency guarantees to implement database leader elections or perform distributed locking across a cluster of workers.

etcd is written in [Go](https://golang.org), which has excellent cross-platform support, small binaries and a great community behind it. Communication between etcd machines is handled via the Raft consensus algorithm.
"""

[params.logos]
hero   = "https://raw.githubusercontent.com/cncf/artwork/master/etcd/horizontal/white/etcd-horizontal-white.png"
cncf   = "https://raw.githubusercontent.com/cncf/artwork/master/cncf/horizontal/color/cncf-color.png"
footer = "https://raw.githubusercontent.com/cncf/artwork/master/etcd/icon/color/etcd-icon-color.png"
panel  = "https://raw.githubusercontent.com/cncf/artwork/master/etcd/icon/color/etcd-icon-color.png"

[[params.features]]
title = "Simple interface"
description = "Read and write values with curl and other HTTP libraries"

[[params.features]]
title = "Key-value storage"
description = "Store data in directories, similar to a filesystem"

[[params.features]]
title = "Watch for changes"
description = "Watch a key or directory for changes and react to the new values"

[[params.fonts]]
name = "Source Sans Pro"
sizes = [300,400,600,700]

[[params.fonts]]
name = "Fira Mono"
sizes = [300,400,600,700]
